### ISSUE TITLE
MOS service

### ISSUE THREAD

**Issue by akrherz** [akrherz/iem-web-services#1]
The [IEM MOS](https://mesonet.agron.iastate.edu/mos/) webpage lists a CSV emitting service that should be centralized into this project.  An IEM user requested the following also be supported with this service.

- [ ] option to only return the latest run of the GFS and NAM
- [ ] allow specification of more than one station

**Comment by henrycluker** [comment]
To add on to this, I'd also like to request to see if we can add NBM (National Blend of Models) data to the ingest for this. It's still [seemingly experimental](https://www.weather.gov/mdl/nbm_text), but here's the [folder](https://sats.nws.noaa.gov/~downloads/nbm/bulk-text/current/) of all the current runs. I could see a lot of data with this being used elsewhere on the site as well.

**Comment by akrherz** [comment]
@henrycluker in general, my ingest is done based on what is available on NOAAPort.  I don't think these NMB text files are available there.  Adding a download and process of these files is appealing though.

**Comment by akrherz** [comment]
@hluker some API examples for you to try

- https://mesonet.agron.iastate.edu/api/1/mos.txt?station=KDSM&model=GFS
- https://mesonet.agron.iastate.edu/api/1/mos.txt?station=KDSM&model=NAM&station=KAMW

There's also a `mos.json` variant with resulting data in JSON Table Schema.

**Comment by hluker** [comment]
This is great. Thanks so much.
