### ISSUE TITLE
Ability to select whether to return all sites or active sites 

### ISSUE THREAD

**Issue by hluker** [akrherz/iem-web-services#4]
I wanted to inquire whether bd7de2f9d35fefa77962d3c04f4e0467f132cb5b in the currents API could potentially be managed via URL parameter as opposed to being hardcoded. My relatively poor excuse of code currently parses by a fixed set of active stations, and alas ORC being returned to the list broke a few things. I believe there might be use cases on both ends of the spectrum?

**Comment by akrherz** [comment]
Thanks for reaching out.  Please define what you mean by 'active'?  Prior to the change, it was stations that had reported within the past two days, approximately.

**Comment by hluker** [comment]
As far as "active," I like the ranges you used for the colors here: https://github.com/akrherz/iem/blob/2dcc2fd5f36373a621fb262235cabdfe02920d53/htdocs/ASOS/current.phtml#L217-L230 -- looks like two hours before they're considered stale? Perhaps it could be configurable, especially when considering the network (faster updating networks like RWIS may have a lower stale time than slower networks like ASOS).

**Comment by akrherz** [comment]
In the case of `ORC`, that was just an omission on my part and should have been removed.  I have also added some code that should remove sites that are flagged as offline.  If I added an `hours=XX` option, would that be sufficient to filter sites only with obs within the past XX hours?

**Comment by hluker** [comment]
Absolutely, that would be perfect.

**Comment by akrherz** [comment]
OKay, you can now set `minutes=xx` to specify the max latency of the last observation.

**Comment by hluker** [comment]
Great! Thank you so much!
